# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/nx-cugraph/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/nx-cugraph/labels

benchmarks:
  - changed-files:
      any-glob-to-any-file:
        - 'benchmarks/**'
ci:
  - changed-files:
      any-glob-to-any-file:
        - 'ci/**'
conda:
  - changed-files:
      any-glob-to-any-file:
        - 'conda/**'
