# This file controls which features from the `ops-bot` repository below are enabled.
# - https://github.com/rapidsai/ops-bot

auto_merger: true
branch_checker: true
label_checker: true
release_drafter: true
forward_merger: true

# enables/disables the Recently Updated Check
recently_updated: true

# sets the threshold for how many commits behind the pull request must be to trigger a failure.
# defaults to 5 if not set
recently_updated_threshold: 5
